[tool.poetry]
name = "benchmark"
version = "0.1.0"
description = ""
authors = ["Nick Hale <nick@acorn.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.1.1"
jsonschema = "^4.21.1"
requests = "^2.31.0"
openai = "^1.16.1"
pydantic = "2.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--junitxml=benchmark_report.xml"  # Path for the generated JUnit report